name: passnat
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 30 16 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run passnat
        env:
          PASSNAT_PHONE: ${{ secrets.PASSNAT_PHONE }}
          PASSNAT_PASSWORD: ${{ secrets.PASSNAT_PASSWORD }}
